### ISSUE TITLE
Progress towards primitive equations

### ISSUE THREAD

**Issue by milankl** [SpeedyWeather/SpeedyWeather.jl#192]
Quick overview where we are in terms of a primitive equation dynamical core and parameterizations

Dynamical core
- [x] Geopotential calculation #188 
- [x] Virtual temperature #197 
- [x] Gradients of (logarithm of) surface pressure #189 
- [x] Layer thickness-weighted vertical averages of u,v,div #189 
- [x] Vertical velocity / mass fluxes #191 
- [x] vertical advection #198 #211 
- [x] pressure gradient terms #198
- [x] log surface pressure tendency #204  
- [x] temperature equation #205 #210 
- [x] add kinetic energy to geopotential #196 
- [x] realistic initial conditions #249  
- [x] semi-implicit corrections #251
- [x] bug hunting #256 #265 

Parameterizations

- [x] Surface drag #269 
- [x] Held Suarez temperature relaxation #270 
- [x] Shortwave radiation #169 
- [x] Longwave radiation #177 
- [x] Large scale condensation #82 
- [x] Convection #128 #414
- [x] Surface fluxes #399 
- [x] Soil temperature #399
- [x] Vertical diffusion

@maximilian-gelbrecht @white-alistair @dmey

**Comment by milankl** [comment]
I hope I can tick off many of the dynamical core parts in the next two weeks, but some things seem to be trickier than I originally thought: For example our structure of the `DiagnosticVariables` split into layers makes absolute sense for many parts of the dynamical core, but not for the vertical advection (used for u,v,T,q), which is a bit annoying. I need to see what's the best to implement that (naive Fortran-SPEEDY copy vs a restructured version with some parallelisation in mind). I'm currently tending towards a naive copy.

**Comment by milankl** [comment]
- Virtual temperature: Easy $T_v = T(1+\mu q)$, but it's currently unclear to me whether this is needed in spectral or grid-point space or both or when to compute it to avoid a spectral transform of the fields.
- Vertical advection: Medium, it's not that tricky, but the vertical advection operator acts across layers, and I don't know yet how to structure this given that we currently work mostly on layers with `diagn.layers[k].grid_variables.var_name`
- pressure gradient terms: Medium, the gradients are already computed for surface pressure tendency and the geopotential too, but it still may require some thinking.
- temperature equation: Medium, the implementation should be straight forward, but the maths will take me a bit to get my head around
- add kinetic energy to geopotential: Easy, that's very similar to how it's done in the shallow water model
- semi-implicit corrections: Harder, as the maths will be adapted to the scaling of our equations and if it's not implemented correctly then things will keep blowing up as the gravity waves aren't dampened.

about the physics: You or @dmey probably know better than me.

**Comment by maximilian-gelbrecht** [comment]
> * Vertical advection: Medium, it's not that tricky, but the vertical advection operator acts across layers, and I don't know yet how to structure this given that we currently work mostly on layers with `diagn.layers[k].grid_variables.var_name`

Don't know how the vertical operators exactly look like, but I wrote those `get_var` functions for the `PrognosticVariables` with output / setting initial conditions in mind. For working with the layers like that, it might be worth it to write non-allocating versions that return views where needed.

**Comment by milankl** [comment]
No date, it's done when it's done. I'm just happy that everyone contributes, whenver that is. Happy for you to start on those you suggested. I don't mind being more involved with vertical diffusion and/or ocean mixed-layer, but I won't focus on them before the dynamical core is up and running reliably.

**Comment by milankl** [comment]
With #251 merged (that was painful!) technically the drycore is now complete 🥳 However, there are still some bugs/errors in the explicit terms: T63 8levels after ~12 days, vorticity in lowest layer, top: with semi-implicit time stepping and 3x the time step, bottom: without. 

![image](https://user-images.githubusercontent.com/25530332/225380126-b84c1f3a-1822-4668-b522-00c2ced80549.png)

So the semi-implicit time stepping does its job, but the error occurs somewhere else.

**Comment by milankl** [comment]
Moving this to v0.6 milestone as what I had intended for v0.5 is basically completed. I believe there's still something wrong as outlined in #309 but that's not for now.

**Comment by milankl** [comment]
Although there are still bits and bobs missing, overall the primitive equation dynamical core is completed and so I'm closing this issue in favour of other more specific issues.
